### ISSUE TITLE
 Toggle math align: add new line when math is in the middle of the line?

### ISSUE THREAD

**Issue by lucasvreis** [iyefrat/evil-tex#10]
The current behaviour of evil-tex-toggle-math-align, in the `\[ ... \]` to `\begin{align*} ... \end{align*}` direction, is to add a new line when a new line is *already present* before the block:

https://github.com/iyefrat/evil-tex/blob/87445d4d2339436179e792609bfbff0eaf056a9c/evil-tex.el#L551

Maybe I am missing something, but shouldn't this equality be negated? I would expect it to add a new line when I'm writing `bla bla bla \(e = mc^2\)` in the middle of a line instead.

**Comment by ymarco** [comment]
Fixed in 181c643, thanks for the catch. I added you as the author, couldn't take credit for it myself
