### ISSUE TITLE
I think there is something messed up with the delimiter keymap.

### ISSUE THREAD

**Issue by jsilve24** [iyefrat/evil-tex#11]
**Steps to reproduce:** 

1. Open new scratch buffer
2. turn on latex-mode
3. turn on evil-tex-mode
4. type "\left[assdf\right]"

With curror between surrounding \left[ and \right] type "dsdB" which per readme should delete the the surrounding pair.. Instead it adds surrounding curly braces "{\left[assdf\right]}"

"dsdd" (note extra d) does bring up the delimiter menu but any key press adds a delimiter. Also the keys indicated are not the same as those in the readme. 

Am I missing something obvious?

**Comment by jsilve24** [comment]
Note I can change delimiters no problem just as the documentation suggests. 

That said, the keymap is very different than the readme. Plus whats weird is that "csd" doesn't ask for the type of delimiter which is asymetric with the syntax for adding a delimiter and just odd IMHO.

**Comment by ymarco** [comment]
dsd shouldn't ask for the delimiter type too.

> 1 Open new scratch buffer
> 2 turn on latex-mode
> 3 turn on evil-tex-mode
> 4 type "\left[assdf\right]"
> do dsdB

I can't reproduce, for me dsd deletes the \left[\right] straight away and doesn't wait for B.

**Comment by jsilve24** [comment]
Ok I figured it out. I had this in my config and it was screwing this up.   ;; deal with whitespace polluting kill-ring

```
  ;;from here: https://emacs.stackexchange.com/questions/39434/evil-dont-yank-with-only-whitespace-to-register
  (define-key evil-normal-state-map "x" 'delete-forward-char)
  (define-key evil-normal-state-map "X" 'delete-backward-char)
  (evil-define-operator evil-delete-without-register-if-whitespace (beg end type reg yank-handler)
    (interactive "<R><y>")
    (let ((text (replace-regexp-in-string "\n" "" (filter-buffer-substring beg end))))
      (if (string-match-p "^\\s-*$" text)
	  (evil-delete beg end type ?_)
	(evil-delete beg end type reg yank-handler))))
  (define-key evil-normal-state-map "d" #'evil-delete-without-register-if-whitespace)
```

now dsd works but I still wonder why it doesn't ask for the delimiter... Wouldn't that be more symmetric and potentially increase flexibility?

**Comment by ymarco** [comment]
Delimiter selection is only for inserting, that's what we decided. Dynamic delimiters.
If you wanna change it, the bindings are at evil-tex-{inner,outer}-text-objects-map.

**Comment by jsilve24** [comment]
Thanks!
