### ISSUE TITLE
Possibly misleading documentation

### ISSUE THREAD

**Issue by redpanda1234** [iyefrat/evil-tex#13]
Thanks for making this package, it's really awesome! 

One minor thing: In the showcase, I think it's not super clear for a newcomer to `evil`-flavored packages that the `cs<...>` commands are implicitly relying on `evil-surround` (I may or may not have spent almost 5 hours trying to figure this out...haha). I know it's mentioned in the summary at the top ("Provides many text objects fully utilizing evil-surround [...]") but it's easy to misunderstand what that means given that the only other mention of `evil-surround` later is 
> `evil-tex` does not require, but supports evil-surround [...]

I'd suggest just adding a line that says "With `evil-surround-mode`: " before all the `cs<...>` commands in the showcase.

Thanks again, the package rocks!

**Comment by ymarco** [comment]
I think iyefrat and I were so familiar with evil-surround when writing this that we took it for granted that anyone knows "cs" means evil-surround.

Sorry for the misunderstanding! It's mentioned twice more now.
