### ISSUE TITLE
Conflicts with evil-colemak-basics

### ISSUE THREAD

**Issue by ninjaguppy** [iyefrat/evil-tex#14]
I am relatively new to emacs and working with Elisp. I am trying to get evil-tex and evil-colemak-basics both working in doom emacs. Evil-colemak-basics maps evil-backwards-character to `m` but this obviously conflicts with evil-tex. Is it it possible to re-map all of evil-tex's "m" commands to `h`?

**Comment by ymarco** [comment]
Try this? It should override all keybinds to evil-set-marker instead of
overriding "m" directly.

If it work for you I'll change it upstream too.

(with-eval-after-load 'evil-tex
  (evil-define-key 'normal evil-tex-mode-map [remap evil-set-marker]
    (evil-tex-dispatch-single-key ?t #'evil-tex-read-and-execute-toggle
                                  'evil-tex-m-functions)))

**Comment by ninjaguppy** [comment]
I tried putting that in my config.el (as well as my init.el just in case) and neither of them worked---evil-tex's `m` is still overriding the evil-colemak-basic commands.

**Comment by ymarco** [comment]
Ah, please set evil-tex-toggle-override-m to nil.

The code I wrote (which should go in your config.el) is concerned with overriding the real evil-set-marker binding -- does that work? Can you do for example "htm" to toggle inline↔display math?

**Comment by ninjaguppy** [comment]
That worked perfectly! Thank you so much!

**Comment by ymarco** [comment]
Lucas Kerbs ***@***.***> writes:



Oh yeah, please set evil-tex-toggle-override-m to nil.
My code piece just makes it override whatever keybinding evil-colemak-basic has for evil-set-marker -- does that work? Can you toggle stuff on "htX"? e.g "htm" to toggle math

(All code should go in .doom.d/config.el)

**Comment by ninjaguppy** [comment]
The other day I updated everything for the first time in months. Everything in the package (htX, etc) still still works with the exception of `cim` for change inner math. I'm not sure if the change you helped me make above is causing that, but I figured I'd let you know and see if you had any ideas!
