### ISSUE TITLE
Is it possible to add a toggle from display math to equation* ? 

### ISSUE THREAD

**Issue by maikol-solis** [iyefrat/evil-tex#21]
Following this discussion (https://tex.stackexchange.com/a/154968/42627) the `align*` environment add too much horizontal and vertical space in the text (besides other glitches).  

A natural toggle for `mtM` (or another key) could be `equation*` to preserve the compactness in the text. 

What do you think?

**Comment by maikol-solis** [comment]
Thanks for your answer. 

> is there any difference between \\[...\\] display math and equation* envs? I just always use \\[...\\], I don't see the need for toggling between that and equations*s.

[Technically, there are no difference when amsmath is loaded](https://tex.stackexchange.com/a/40531/42627), but I found very easy to toggle `equation*` to `equation` (`mte`) if I want it numbered.  

But yes, the `csmeE(e)` options are fine too.

**Comment by ymarco** [comment]
Closing due to lack of discussion
