### ISSUE TITLE
Regex too permissive

### ISSUE THREAD

**Issue by acristoffers** [iyefrat/evil-tex#3]
The regex defined in 

```
(defvar evil-tex--section-regexp
  "\\\\\\(part\\|chapter\\|subsubsection\\|subsection\\|section\\|subparagraph\\|paragraph\\)\\*?"
  "Regexp for matches for LaTeX heading markup.")
```

is too permissive. In my code, I have the command `\partial`, used for derivatives, and it is matching with `\part`.
My suggestion is to add `\*?[\[{]` to the end of the regex (`\*?` is already there) so it only matches if it is the actual environment, and stops matching partially.

**Comment by ymarco** [comment]
Isn't adding `\>` (denotes the end of a word boundry) enough? These parentheses types are not strictly necessary after `\section`/`\subsection`/... and I'd rather avoid regexes that are hard too read (took me like a minute to figure yours out).

**Comment by acristoffers** [comment]
It is mandatory, as far as I know. Try to compile this:

```
\documentclass{article}

\begin{document}
    \section

    hi
\end{document}
```

**Comment by iyefrat** [comment]
This compiles, with "h" as the section title and "i" as the section body. you seem to be able to have arbitrary whitespace between the `section` and the `{title}` if you want, so word boundary sounds like the best way to go.

**Comment by iyefrat** [comment]
Well, to be precise the exact thing you sent does not really compile nicely because the `hi` is on another line, what I referred to was happens on `\section hi`. But you can still do things like `\section                      {hi}` so we still need to consider possible whitespace.

**Comment by acristoffers** [comment]
`\section {something}` is a good point. I'll change the pull-request.

**Comment by acristoffers** [comment]
I squashed all commits together and changed the regex to word-boundary.

What is fixed exactly:

- Requires `\section`, `\subsection`, etc to be a whole word, so `\part` stops matching `\partial`.
- For files that are not the root document, matches end of buffer too, so the selection on the last heading works.
