### ISSUE TITLE
Bind text-objects to mode keymaps

### ISSUE THREAD

**Issue by acristoffers** [iyefrat/evil-tex#5]
In hlissner/doom-emacs#4265, I report that two keybindings are conflicting. He suggests the fix be made upstream since the reason I'm getting a non-deterministic behaviour is evil-tex's keybindings not being bound to the mode's keymaps, which has higher precedence.

So, if all evil-tex's keybindings are bound to latex-mode's keymaps, everyone editing a latex file will get evil-tex functionality 100% percent of the time, and not randomly like I'm getting.

Sorry for not presenting a PR, but I'm on a tight schedule :/

**Comment by ymarco** [comment]
If you look at [the code](https://github.com/iyefrat/evil-tex/blob/ac313efb22d621c093d8d30233bd7dc8b4cc54b4/evil-tex.el#L876-L883), the keymaps *are* bound locally to `evil-tex-(inner|outer)-text-objects-map`, as long as you have a recent enough version of evil-surround (which Doom should).

**Comment by acristoffers** [comment]
Indeed they are. I don't know why that specific command is being overwritten _sometimes_. I'll close since I have no idea what is going on and Lissner's shot was wrong.
