### ISSUE TITLE
Adding double quotes as a delimiter

### ISSUE THREAD

**Issue by justbur** [iyefrat/evil-tex#6]
First, thank you for this package!

I would like to add latex's weird double quotes, ```` `` ```` and `''`, as delimiters, but everything I've tried, including 

```elisp
(evil-tex-bind-to-delim-map '(("q" "``" . "''")))
```
doesn't seem to have the effect I was looking for (being able to select and manipulate these quotations as text objects). 

Is this possible?

**Comment by ymarco** [comment]
The delimiter keymap is used only for delimiter insertion with evil-surround.
The logic for manipulating them as text objects is in evil-tex--select-delim.

Honestly, I don't think ``'' quotes fit in class with the rest of these delimiters. Creating a text object for them doesn't involve nearly as much hassle as what we go through there.

I'd suggest doing it the the normal evil method for creating text objects. Inspiration from the early days of evil-tex:

(evil-define-text-object evil-tex-inner-math (count &optional beg end type)
  "Select innter \\[ \\] or \\( \\)."
  :extend-selection nil
  (evil-select-paren "\\\\\\[\\|\\\\(" "\\\\)\\|\\\\\\]" beg end type count nil))

(evil-define-text-object evil-tex-a-math (count &optional beg end type)
  "Select a \\[ \\] or \\( \\)."
  :extend-selection nil
  (evil-select-paren "\\\\\\[\\|\\\\(" "\\\\)\\|\\\\\\]" beg end type count t))

(define-key evil-inner-text-objects-map "m" 'evil-tex-inner-math)
(define-key evil-outer-text-objects-map "m" 'evil-tex-a-math)

**Comment by justbur** [comment]
Ok thanks. I had a bunch of these text objects defined in my config before I found this package so I can certainly resurrect some of them. I just initially thought that there was a way to handle this using a function here, but no problem.

**Comment by agenbite** [comment]
This package is great, and makes life much easier for dummies (like me). It is surprising that such a common thing as the latex double quotes are not considered for insertion in evil-tex.

I tried to make sense of the chain of backslashes in your examples, @ymarco, but I couldn't understand what's going on. Maybe @justbur can share the solution they ended up with? :)

Thanks so much for the package, anyway!

**Comment by ymarco** [comment]
> I tried to make sense of the chain of backslashes in your examples, @ymarco, but I couldn't understand what's going on.
The regexes are equivalent to 
```emacs-lisp
(regexp-opt (list (regexp-quote "\\(") (regexp-quote "\\[")))
(regexp-opt (list (regexp-quote "\\)") (regexp-quote "\\]")))
```
If that's any help. Regexes matching `` and '' should be considerably simpler.

> It is surprising that such a common thing as the latex double quotes are not considered for insertion in evil-tex.

It just never came up. (The LaTeX I happen to write is in Hebrew which doesn't do these quotes, and when I write in English I do it in Org which exports normal "" as `` ''.) 
I guess we'll accept a PR. Where do we bind it though? It would be nice to make ' a dwim binding that selects all quotes. Or maybe "? But ' already selects both ' and " quotes for me, both in vim and evil-mode, despite both their docs saying ' and " should be different. What?

**Comment by agenbite** [comment]
Fair enough, yes. I understand now. Thanks for the answer (and the package). :)
